# Numpy - Works with array

In [2]:
import numpy as np 

print(np.__version__)

1.26.4


In [2]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [3]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2D)
print('number of dimensions :', arr2D.ndim)
print('shape :', arr2D.shape)
print(arr2D[0, 1])

[[1 2 3]
 [4 5 6]]
number of dimensions : 2
shape : (2, 3)
2


dtype
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [32]:
# shape
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
# reshape to 1D
new = arr2D.reshape(1, -1).T
new

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
# iterating arrays using nditer
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

# ndenumerate
arr = np.array([[1,2,3],[4,5,6]])
for idx, num in np.ndenumerate(arr):
    print(idx, num)

1
2
3
4
5
6
7
8
b'1'
b'2'
b'3'
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [49]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr2 = np.array([[[17, 18, 19], [110, 111, 112]], [[19, 29, 39], [49, 59, 69]]])

# join arrays
newarr = np.concatenate((arr, arr2), axis=-1)
newarr

array([[[  1,   2,   3,  17,  18,  19],
        [  4,   5,   6, 110, 111, 112]],

       [[  7,   8,   9,  19,  29,  39],
        [ 10,  11,  12,  49,  59,  69]]])

In [50]:
# join by stack
newarr = np.stack((arr, arr2), axis=0)
newarr

array([[[[  1,   2,   3],
         [  4,   5,   6]],

        [[  7,   8,   9],
         [ 10,  11,  12]]],


       [[[ 17,  18,  19],
         [110, 111, 112]],

        [[ 19,  29,  39],
         [ 49,  59,  69]]]])

In [51]:
#hstack
newarr = np.hstack((arr, arr2))
newarr

array([[[  1,   2,   3],
        [  4,   5,   6],
        [ 17,  18,  19],
        [110, 111, 112]],

       [[  7,   8,   9],
        [ 10,  11,  12],
        [ 19,  29,  39],
        [ 49,  59,  69]]])

In [52]:
# vstack
newarr = np.vstack((arr, arr2))
newarr

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]],

       [[ 17,  18,  19],
        [110, 111, 112]],

       [[ 19,  29,  39],
        [ 49,  59,  69]]])

In [53]:
# dstack
newarr = np.dstack((arr, arr2))
newarr

array([[[  1,   2,   3,  17,  18,  19],
        [  4,   5,   6, 110, 111, 112]],

       [[  7,   8,   9,  19,  29,  39],
        [ 10,  11,  12,  49,  59,  69]]])

In [5]:
# split
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [4]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [6]:
## Searching in array

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [17]:
# searchsorted
arr = np.array([6, 8, 9, 7])

x = np.searchsorted(arr, 7)
x


1